In [1]:
import pandas as pd

In [6]:
df = pd.read_pickle("test.csv")

In [7]:
df.head()

,algo_volatility,algorithm_period_return,alpha,benchmark_period_return,benchmark_volatility,beta,capital_used,ending_cash,ending_exposure,ending_value,...,short_exposure,short_value,shorts_count,sortino,starting_cash,starting_exposure,starting_value,trading_days,transactions,treasury_period_return
2006-01-03 21:00:00+00:00,NaN,0.0,None,0.0,NaN,None,0.0,100.0,0.0,0.0,...,0.0,0.0,0,NaN,100.0,0.0,0.0,1,[],0.0
2006-01-04 21:00:00+00:00,0.0,0.0,None,0.0,0.0,None,0.0,100.0,0.0,0.0,...,0.0,0.0,0,NaN,100.0,0.0,0.0,2,[],0.0
2006-01-05 21:00:00+00:00,0.0,0.0,None,0.0,0.0,None,0.0,100.0,0.0,0.0,...,0.0,0.0,0,NaN,100.0,0.0,0.0,3,[],0.0
2006-01-06 21:00:00+00:00,0.0,0.0,None,0.0,0.0,None,0.0,100.0,0.0,0.0,...,0.0,0.0,0,NaN,100.0,0.0,0.0,4,[],0.0
2006-01-09 21:00:00+00:00,0.0,0.0,None,0.0,0.0,None,0.0,100.0,0.0,0.0,...,0.0,0.0,0,NaN,100.0,0.0,0.0,5,[],0.0

In [8]:
df.tail()

,algo_volatility,algorithm_period_return,alpha,benchmark_period_return,benchmark_volatility,beta,capital_used,ending_cash,ending_exposure,ending_value,...,short_exposure,short_value,shorts_count,sortino,starting_cash,starting_exposure,starting_value,trading_days,transactions,treasury_period_return
2019-12-24 18:00:00+00:00,0.177320,1.476972,None,0.0,0.0,None,0.0,88.39715,159.3,159.3,...,0.0,0.0,0,0.651571,88.39715,158.6,158.6,3519,[],0.0
2019-12-26 21:00:00+00:00,0.177299,1.488972,None,0.0,0.0,None,0.0,88.39715,160.5,160.5,...,0.0,0.0,0,0.654278,88.39715,159.3,159.3,3520,[],0.0
2019-12-27 21:00:00+00:00,0.177274,1.491972,None,0.0,0.0,None,0.0,88.39715,160.8,160.8,...,0.0,0.0,0,0.654882,88.39715,160.5,160.5,3521,[],0.0
2019-12-30 21:00:00+00:00,0.177249,1.488972,None,0.0,0.0,None,0.0,88.39715,160.5,160.5,...,0.0,0.0,0,0.654091,88.39715,160.8,160.8,3522,[],0.0
2019-12-31 21:00:00+00:00,0.177228,1.478972,None,0.0,0.0,None,0.0,88.39715,159.5,159.5,...,0.0,0.0,0,0.651653,88.39715,160.5,160.5,3523,[],0.0